services:
  envoy:
    image: envoyproxy/envoy:v1.32.3
    command: envoy -c /etc/envoy.yaml -l debug --service-cluster envoy
    # build:
    #   context: .
    #   dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    # expose: #no need, the other services don't communicate with envoy
    #   - "8001"
    #   - "8010"
    ports:
      - "8001:8001"
      - "8010:8010"
      - "8020:8020"
    # network_mode: host
  backend:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - envoymesh
    expose:
      - "8123"
    # ports: not needed on host netw unless debugging
    #   - "8123:8123"
    # network_mode: host
  backend2:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - envoymesh
    expose:
      - "8123"
  backend-ws:
    image: ghcr.io/vi/websocat
    command: -s 0.0.0.0:8765
    networks:
      - envoymesh
    expose:
      - "8765"
  access_log_service:
    image: envoy_access_logs:v0.3.2
    networks:
      - envoymesh
    expose:
      - "18000"
networks:
  envoymesh: {}
