services:
  envoy:
    image: docker.ops.iszn.cz/labrador/envoy:1.32.3-szn1
    command: envoy -c /etc/envoy.yaml -l debug --service-cluster envoy
    # build:
    #   context: .
    #   dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8001"
      - "8010"
    ports:
      - "8001:8001"
      - "8010:8010"
  backend:
    # image: nginx:latest
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: backend
    networks:
      - envoymesh
    expose:
      - "8123"
    ports:
      - "8123:8123"
  access_log_service:
    image: envoy_access_logs:v0.3.2
    networks:
      - envoymesh
    expose:
      - "18000"
    ports:
      - "18000:18000"
networks:
  envoymesh: {}
